### PR TITLE
Development 1.1 calender

### PR DESCRIPTION
**Pull request by maayarosama**
### Related Issues
#265

### CODE REVIEW

**Comment by Mahmoud-Emad** [comment]
Why do we do all these requests??
image

we didn't do that in the old client

image

**Comment by Mahmoud-Emad** [comment]
The meeting link should open in another window

image

use `target= _blank` to achieve that

**Comment by Mahmoud-Emad** [comment]
The current calendar doesn't display `Birthdates` or `Publick holidays`

- image

**Comment by Mahmoud-Emad** [comment]
Clicking outside the dialog and on the `Exc` key should close it 

  [Screencast from 01-23-2024 11:55:58 PM.webm](https://github.com/codescalers/CSHR/assets/57001890/d95dbbac-33e3-4a7e-a785-0bcdba6959cd)

**Comment by Mahmoud-Emad** [comment]
Does this card need a background?

- image

**Comment by Mahmoud-Emad** [comment]
The request should be based on the chosen month, and we should show a loading indicator until the events have loaded.

[Screencast from 01-23-2024 11:58:36 PM.webm](https://github.com/codescalers/CSHR/assets/57001890/4cc47bb8-f686-41ec-957d-7d47850e7d20)

**Comment by Mahmoud-Emad** [comment]
Does this need to be changed? The color I mean

[Screencast from 01-24-2024 12:01:05 AM.webm](https://github.com/codescalers/CSHR/assets/57001890/63c98e5c-20de-4eba-816c-80da8d851747)

**Comment by maayarosama** [comment]
> Does this need to be changed? The color I mean
> 
>  Screencast.from.01-24-2024.12.01.05.AM.webm

@ehab-hassan Should be handling any styling issues(colors, fonts, etc..)

**Comment by maayarosama** [comment]
> Why do we do all these requests?? image
> 
> we didn't do that in the old client
> 
> image

it's because we're retrieving every user that applied for a vacation to display his/her name in the title, this feature was discussed in the demo and approved by @xmonader

**Comment by Mahmoud-Emad** [comment]
image
got this error when clicked on the vacation event

**Comment by Mahmoud-Emad** [comment]
did you miss the birth date events?

image

**Comment by Mahmoud-Emad** [comment]
I got this error after clicking on the `Public Holiday` event, maybe we need a detail card there

image

**Comment by ehab-hassan** [comment]
> > Does this need to be changed? The color I mean
> > Screencast.from.01-24-2024.12.01.05.AM.webm
> 
> @ehab-hassan Should be handling any styling issues(colors, fonts, etc..)

ll handle all styling and color when merged to development_1.1

**Pull request merged**
